const SET_SIGNATURE = "SET_SIGNATURE";
const CLEAR_SESSION = "CLEAR_SESSION";
const SET_USER_INFO = "SET_USER_INFO";
const SET_IS_LOADING = "SET_IS_LOADING";
const SET_CURRENCY = "SET_CURRENCY";
const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
const SET_SHIPROCKET_TOKEN = "SET_SHIPROCKET_TOKENET_CATEGORY_LIST";
const SET_CART_FLAG = "SET_CART_FLAG";
export {
    SET_SIGNATURE,
    CLEAR_SESSION,
    SET_USER_INFO,
    SET_CURRENCY,
    SET_CATEGORY_LIST,
    SET_SHIPROCKET_TOKEN,
    SET_CART_FLAG
}